- name: Creating ssh keys for connecting
  hosts: localhost
  connection: local
  roles:
    - ssh_keygen

- name: Create user and configure nginx
  hosts: webserver
  remote_user: vagrant
  become: yes
  roles:
    - users
    - nginx
